version: 0.2

phases:
  build:
    commands:
      - exit 1
      - echo Building SpringBoot App...
      # - java -junit /test
      # - junit covarage 
      - cd app 
      - chmod +x mvnw
      - export MAVEN_OPTS="-Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"
      - ./mvnw clean install -U || sleep 30 && ./mvnw clean install
      - mv target/*.war target/sample-java-app.war
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - app/target/sample-java-app.war
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes