version: 0.2

phases:
  build:
    commands:
      - echo Building SpringBoot App...
      - cd app 
      - chmod +x mvnw
      - ./mvnw clean install
      - ls target

artifacts:
  files:
    - target/sample.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no