version: 0.2

phases:
  build:
    commands:
      - echo Building SpringBoot App...
      - cd app 
      - chmod +x mvnw
      - ./mvnw clean install
      - mv target/sample-springboot-app-0.0.1.war target/abc.war


artifacts:
  files:
    - app/target/abc.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no