page:
  home: http://localhost:8080/
server:
  port: 8080
spring:
  application:
    name: MultiTenant
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    add-properties: true